# Generated by Django 2.2.6 on 2019-10-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_method',
            field=models.CharField(choices=[('OVEN', 'Oven'), ('STOVE', 'Stove'), ('MICROWAVE', 'Microwave')], default='MICROWAVE', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
