# Generated by Django 2.2.6 on 2019-10-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191023_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cool_temp',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
