# Generated by Django 2.2.6 on 2019-10-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191023_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cool_temp',
            new_name='cook_temp',
        ),
    ]
